### ISSUE TITLE
An error when creating tool scripts for the first time.

### ISSUE THREAD

**Issue by ghost** [ballerburg9005/godot-metadata-inspector#4]
1. ~~Your entire project, or a demo project that produces the same bug.~~
N/A

2. The version of Godot and Metadata Inspector.
0.2.1 9c73d9e74eb9ef2710d3618f03f9249e37e59580

3. Exact steps to reproduce the bug.
On some occasions when adding `tool` to a script for the first time and then saving, the following error appears.
![godot windows tools 64_jipJfIECGx](https://user-images.githubusercontent.com/13004169/87849540-19e06a80-c8f2-11ea-9cb2-9293d07b62f3.png)

**Comment by ballerburg9005** [comment]
That is pretty weird. 

Try the most recent commit.

**Comment by ghost** [comment]
So far so good, it appears to be resolved.  I could be wrong about the conditions to recreate it, like that debugger problem earlier.

Can't reproduce from the current head.  Fingers crossed.  🤞 

I'll leave a breakpoint in case it reappears, and if it comes back I'll see what I can trace.
