### ISSUE TITLE
Metadata Inspector Messes Up Focus Priority when Selecting Nodes

### ISSUE THREAD

**Issue by Lucrecious** [ballerburg9005/godot-metadata-inspector#5]
**Repro Steps:**

1. Open a new project in Godot
2. Create a 2D scene
3. Download and Install Metadata Inspector
4. Enable Metadata Inspector 
5. Select nothing by clicking in empty space in the 2D view
6. Click on the default Node2D in the Scene Tree

**Expected:**
Scene Tree dialog is highlighted
**Actual:**
Scene Tree dialog is not highlighted

Repeat the same repro up to step 5.
Then.
6. Click on the default Node2D in the 2D view

**Expected:**
2D view is highlighted
**Actual:**
2D view is not highlighted

It's important to note, that this is not regular Godot behaviour and interferes with Godot hotkeys and other plugin hotkeys.

For example, because of this, hotkeys that are supposed to work in the 2D view, do not work after step 6 because the 2D view is not in focus. This is only a problem when this plugin is enabled since, for some reason, when you select a node, it puts something else into focus.

I would put up an example file but this is reproducible on a new Godot project that has the Metadata Inspector installed.

**Comment by ballerburg9005** [comment]
I cannot reproduce it, the exact same way you described it. 

The way you described it, Metadata Inspector would interfere with the focus simply because it is enabled for no good reason. This doesn't seem to be the case.

What I can reproduce is, that the Meta-Tab defaults to grabbing focus once it is opened. If you leave it open and switch nodes it technically opens again for the new node. 

Please confirm that this is what you meant.

**Comment by ballerburg9005** [comment]
What version are you using?

**Comment by Lucrecious** [comment]
I'm using the asset library version for 3.2.

That's weird - I've installed it fresh on a new project, and the bug still occurs with Godot 3.2.2. This doesn't happen when the plugin is disabled. I even verified that it is this plugin causing the issue due to the fact that it switches focus to a textedit control when `update_node` is called. 

Here's a gif of what I'm talking about. Again, this is a fresh project, all I've done is install the metadata inspector and enabled it. You can see that after I select a node the Scene Tree is not highlighted, same when I select a node in the 2D view. I have to click on the node twice for the proper focus to be set (which is what I do once in the beginning of the gif).
![2020-07-27 10 55 07](https://user-images.githubusercontent.com/4584511/88557172-e1c6df00-cff7-11ea-823b-f316775e4498.gif)

Here's a gif without the plugin enabled - this is the correct result. Notice that the Scene Tree is immediately highlighted after I click on the Node, and same with the 2D view, it's immediately highlighted when I click on the Node.
![2020-07-27 10 54 39](https://user-images.githubusercontent.com/4584511/88557240-f60adc00-cff7-11ea-85da-fe831fe0f61f.gif)

**Comment by Lucrecious** [comment]
To be clear, the Metadata Inspector in those gif is not opened, just the regular Inspector. However, even if the Metadata Inspector were opened up, this should not be reproducible.

My opinion is that the Metadata Inspector's Controls should only get focus when the user actually clicks on one of the text edit controls - not when you select a node from the Scene Tree or 2D View (i.e. not when `handles` gets called in the Plugin flow) - the latter is what happens right now.

**Comment by ballerburg9005** [comment]
Here is the fix the way you proposed it. I am not 100% sure yet if I should merge this.

**Comment by Lucrecious** [comment]
Sure, that's completely fair.

Thanks! This is more than enough. I'll leave this open for you to close if you decide.
